<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Curriculum</name>
   <tag></tag>
   <elementGuidId>4c5f614a-5bb2-4ca1-832a-7a07a7e54d4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarNavDropdown']/ul/li[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav.navbar-nav > li:nth-of-type(8) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Curriculum&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>150e820f-3dd8-4623-b53e-62817632f03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cac.annauniv.edu</value>
      <webElementGuid>369dc2a8-b22e-45c5-98ab-7b2906546488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6182aa7e-e133-4f7b-bee6-30acf134481f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Curriculum</value>
      <webElementGuid>5c1b3fdf-5e7e-442a-8c1f-c600374aaf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarNavDropdown&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[8]/a[1]</value>
      <webElementGuid>473d0ccd-2f32-49e7-8c77-40cb8ed9dc9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarNavDropdown']/ul/li[8]/a</value>
      <webElementGuid>a2faabb8-6d90-4c7e-9266-9541f2619a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Curriculum')]</value>
      <webElementGuid>471ac9e6-9333-485e-8481-42b115da1a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Affiliated Colleges (CoE)'])[1]/following::a[1]</value>
      <webElementGuid>26be5373-344f-4e9e-9fd9-b545fc5ac10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University Campus (ACoE)'])[1]/following::a[2]</value>
      <webElementGuid>667596c3-55a1-4b30-a97a-281b22c11e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admissions'])[1]/preceding::a[1]</value>
      <webElementGuid>2d2f6406-172a-495c-a1a0-36c3d6b5edcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centre for Admissions'])[2]/preceding::a[2]</value>
      <webElementGuid>a1fd69bc-2c8c-4f1c-b944-b1e230fc3509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Curriculum']/parent::*</value>
      <webElementGuid>9a24c404-afa8-4efb-9097-cbedf2ff970b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://cac.annauniv.edu')])[3]</value>
      <webElementGuid>53934873-15f2-4b7a-8f10-a9e97ba62bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li[8]/a</value>
      <webElementGuid>776d3ae2-bdcc-4ab1-8c27-7b58d97395e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cac.annauniv.edu' and (text() = 'Curriculum' or . = 'Curriculum')]</value>
      <webElementGuid>fa6652e9-1a9d-4780-92fd-509d3062e054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
