<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Recruitment</name>
   <tag></tag>
   <elementGuidId>c5839906-90a4-4d45-bb27-34c02f471e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='bg']/div/div/div[2]/div/div/div/div/div/div/div/ul/li[2]/a/span/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a > span.title-head > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=/^Recruitment$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>eff11f25-e3b8-4642-a685-f3f152a4ef0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recruitment</value>
      <webElementGuid>4976a458-63c5-42d1-b57f-8d88a3c97f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bg&quot;)/div[@class=&quot;page-wraper&quot;]/div[@class=&quot;page-content bg-white&quot;]/div[@class=&quot;bg-white tabs-box-area&quot;]/div[@class=&quot;section-full bg-white content-inner&quot;]/div[@class=&quot;section-full bg-white content-inner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;section-content box-sort-in button-example p-t10 p-b30 tabs-site-button&quot;]/div[@class=&quot;dlab-tabs border&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[2]/a[1]/span[@class=&quot;title-head&quot;]/strong[1]</value>
      <webElementGuid>d1ba7361-6a17-4ca5-bec5-4391d02cd1e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bg']/div/div/div[2]/div/div/div/div/div/div/div/ul/li[2]/a/span/strong</value>
      <webElementGuid>8fb8bfa9-a28b-451b-b8dd-1be0d3b4150c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/following::strong[1]</value>
      <webElementGuid>86a83caf-3d99-4645-aaa5-a8dbbdbf7958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News &amp; Events'])[1]/following::strong[2]</value>
      <webElementGuid>31577387-2eed-41d6-a6d4-3178814b24db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FDTP / Workshop / Conference'])[1]/preceding::strong[1]</value>
      <webElementGuid>03224652-34b1-44bd-8392-eaee204631fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tender'])[1]/preceding::strong[2]</value>
      <webElementGuid>f15ff749-59b8-4ceb-b5b3-0f54955eef18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recruitment']/parent::*</value>
      <webElementGuid>b8d98e68-0b1c-4632-a362-ac6778468a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span/strong</value>
      <webElementGuid>388ef8e9-b5ad-4335-9fdb-6de66af88c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Recruitment' or . = 'Recruitment')]</value>
      <webElementGuid>6263bc39-6073-42b3-8a4d-7edbeb43d271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
