<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alumni</name>
   <tag></tag>
   <elementGuidId>ae84302b-7fb4-4278-bfa2-97a1b39b8d5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='bg']/header/div/nav/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a.ripple</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Alumni&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95b8c781-f2b5-4778-a283-2edbff153363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#alumni</value>
      <webElementGuid>167ed700-d73e-47c7-88d3-f82a89ad8b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ripple</value>
      <webElementGuid>441f2793-12ac-4cf0-ac3b-72432d232ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notable Alumni</value>
      <webElementGuid>4a0a1c96-2a6e-4c17-a5c8-22d19a949c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						 Alumni
					</value>
      <webElementGuid>0db1623e-df76-4153-81d2-038f4cbbe91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bg&quot;)/header[1]/div[@class=&quot;page-content bg-white&quot;]/nav[@class=&quot;floating-menu&quot;]/ul[@class=&quot;main-menu&quot;]/li[4]/a[@class=&quot;ripple&quot;]</value>
      <webElementGuid>58fd0bb4-0331-4d32-98b5-4d99987146ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bg']/header/div/nav/ul/li[4]/a</value>
      <webElementGuid>da73ebe2-8aee-42ba-9e1d-350099f8eed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alumni']/parent::*</value>
      <webElementGuid>6aba4115-7b4a-40e9-8e8f-423b2e008105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#alumni')]</value>
      <webElementGuid>bcf7ee4f-cb28-4b7c-a5f5-cb30c16a2337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[4]/a</value>
      <webElementGuid>1c12cd3f-28d8-44b6-a546-e39b0aae07da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#alumni' and @title = 'Notable Alumni' and (text() = '
						 Alumni
					' or . = '
						 Alumni
					')]</value>
      <webElementGuid>de59513c-3013-48f7-abdb-2f53b14328d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
