<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>a8b68f58-f6f0-4adf-b635-a7b4d1ec5b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='bg']/div/header/div/div/div/div/div[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=link[name=&quot;Home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3d129a8-98d9-40cb-a26e-2e7cd9975854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php</value>
      <webElementGuid>b992b92c-4589-465a-abc3-d729c435de0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>e237f2e5-a565-4999-8d6e-683696dbb6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bg&quot;)/div[@class=&quot;page-wraper&quot;]/header[@class=&quot;site-header mo-left header&quot;]/div[@class=&quot;sticky-header main-bar-wraper navbar-expand-lg is-fixed&quot;]/div[@class=&quot;main-bar clearfix&quot;]/div[@class=&quot;top-bar&quot;]/div[@class=&quot;row d-flex justify-content-between align-items-center&quot;]/div[@class=&quot;col-lg-9 dlab-topbar-right text-center&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>81c7e01b-416d-4409-81e6-909e7f33880a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bg']/div/header/div/div/div/div/div[2]/ul/li/a</value>
      <webElementGuid>b006c0f9-1af7-4f9f-8134-0bd528757656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home')]</value>
      <webElementGuid>3f26acbc-1c3d-4875-b8c9-224fa0f5fa6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Translate'])[1]/following::a[1]</value>
      <webElementGuid>4b50fdb2-b5dc-4bad-91c8-1e5535f3e569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports'])[1]/preceding::a[1]</value>
      <webElementGuid>f6670171-142f-4efd-8886-719435025107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IQAC'])[1]/preceding::a[2]</value>
      <webElementGuid>1eabf96b-f293-4b30-9ad3-055bcf25515b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>58f9871a-449d-4e8d-8400-e283efe3ce86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php')]</value>
      <webElementGuid>37ba5c6c-5695-4208-b1d4-b477bc40008e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>95c577d4-472c-4f66-94c1-f7af49b016a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php' and (text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>42198771-dfbb-426c-ae3e-a0c64f11b3f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
