<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notifications</name>
   <tag></tag>
   <elementGuidId>20eb78fa-5342-476a-b402-105d0ab8aa3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='bg']/header/div/nav/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a.ripple</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Notifications&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e027d4ca-f771-4174-a3ea-780d549a3d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.annauniv.edu/events.php</value>
      <webElementGuid>d4bec4a5-e3a4-4ffd-b64f-0936d3127ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ripple</value>
      <webElementGuid>930c7ab3-a33b-4d80-85f4-2b1b1bad2610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>News and Events</value>
      <webElementGuid>ef787714-a64e-495f-9358-fd8497fdd497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a67957f2-38df-4927-b5cf-650b6ab8dc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						 Notifications
					</value>
      <webElementGuid>4b11d945-6372-4e98-8e78-e45587168321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bg&quot;)/header[1]/div[@class=&quot;page-content bg-white&quot;]/nav[@class=&quot;floating-menu&quot;]/ul[@class=&quot;main-menu&quot;]/li[3]/a[@class=&quot;ripple&quot;]</value>
      <webElementGuid>f8dc47d1-0e9d-47ab-a776-4b13b516aaa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bg']/header/div/nav/ul/li[3]/a</value>
      <webElementGuid>dfca410d-1d0e-4411-96a8-4f62eb8dfc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notifications']/parent::*</value>
      <webElementGuid>83de223c-2fe4-4bbf-807e-d461e5c569f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.annauniv.edu/events.php')]</value>
      <webElementGuid>6ca8edfe-05f8-4b6f-a8f0-27430bd7d81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a</value>
      <webElementGuid>074b22d0-f701-4d7c-8243-f39c077581bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.annauniv.edu/events.php' and @title = 'News and Events' and (text() = '
						 Notifications
					' or . = '
						 Notifications
					')]</value>
      <webElementGuid>53225e94-5808-455c-8de4-d86e093060d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
