<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_About Bharathidasan University Alumni A_e84b88</name>
   <tag></tag>
   <elementGuidId>6c27aa2c-afc9-4aeb-9168-3c12f1c14b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) > .card > .bd-placeholder-img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>409a1473-0658-4fdc-9dac-c6f4b7989501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bd-placeholder-img card-img-top</value>
      <webElementGuid>010dba02-916d-4b53-9100-2f15f443811c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>aff75508-eae8-4b3d-b0e2-887fb5db07bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>225</value>
      <webElementGuid>913c740d-86f1-463c-a73b-9729f8b52034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5fa12577-ea28-489a-98db-c559f8548c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/gallery-images/alumni-meet-2018-2.jpg</value>
      <webElementGuid>824edb6d-eee2-4006-a522-b9184b500d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveaspectratio</name>
      <type>Main</type>
      <value>xMidYMid slice</value>
      <webElementGuid>cbf77dda-d800-401e-add0-9f329ac33e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ba0144b6-a056-42fe-8683-4aaf40a781da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid bg-white p-0&quot;]/div[@class=&quot;container my-0&quot;]/div[@class=&quot;row p-4 pb-0 pe-lg-0 pt-lg-3 align-items-center rounded-3 border shadow-lg&quot;]/div[@class=&quot;col-lg-12 p-3 pt-1&quot;]/div[@class=&quot;album py-5 bg-light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;card shadow-sm&quot;]/img[@class=&quot;bd-placeholder-img card-img-top&quot;]</value>
      <webElementGuid>788a4232-03e5-4736-91fb-2f92ef22fb50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>8318b5a6-4c98-4095-9bf7-6137811cf4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/gallery-images/alumni-meet-2018-2.jpg']</value>
      <webElementGuid>8b6327dc-2897-44fb-99b8-b8cb89d8b022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
