<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Tamil</name>
   <tag></tag>
   <elementGuidId>b4c0b0fd-76f2-44e4-af2b-a54c6204d81d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sociology'])[1]/following::td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(27) > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Tamil&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bb278472-b6f0-48ba-9996-3aef716d17ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tamil</value>
      <webElementGuid>9b3b7b1b-b78e-4fe7-9556-89e225eead92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/table[3]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/center[1]/table[1]/tbody[1]/tr[27]/td[2]</value>
      <webElementGuid>08c9a2a2-15ba-41ab-9e1c-716a47e359b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sociology'])[1]/following::td[3]</value>
      <webElementGuid>1f2cb816-e95f-4241-9905-986b418dcf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Political Science'])[1]/following::td[6]</value>
      <webElementGuid>22c28e22-c3d6-4fbe-9bcd-ec093cacde08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University Science Instrumentation Centre'])[1]/preceding::td[3]</value>
      <webElementGuid>f228f7fa-d5fc-49fa-a170-5a9116b7dab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Collections'])[1]/preceding::td[6]</value>
      <webElementGuid>0a2b8adb-90ca-4a32-8764-33390bd8f1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tamil']/parent::*</value>
      <webElementGuid>4a7d3794-d651-415b-a598-dd9e1f2884ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[27]/td[2]</value>
      <webElementGuid>8277c6f7-0cac-4fdd-809e-4c910930a427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Tamil' or . = 'Tamil')]</value>
      <webElementGuid>6f68073a-f2c1-44b5-8788-f9c9f177eff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
